services:
  mariadb:
    image: inception-mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    networks:
      - my_net
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - databasepassword
      - my_sql_rootpassword
      - mysql_user
  
  wordpress:
    image: inception-wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    restart: on-failure
    networks:
      - my_net
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    secrets:
      - databasepassword
      - wp_admin_password
      - wp_user_password
  
  nginx:
    image: inception-nginx
    container_name: nginx
    build: ./requirements/nginx
    restart: on-failure 
    networks:
      - my_net
    volumes:
      - wordpress_data:/var/www/html
    # env_file:
    #   - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    # secrets:
    #   - databasepassword
    #   - wp_admin_password
    #   - wp_user_password

networks:
  my_net:
    driver: bridge


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ayoakouh/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ayoakouh/data/wordpress
      o: bind

secrets:
  databasepassword:
    file: ../secrets/databasepassword
  my_sql_rootpassword:
    file: ../secrets/my_sql_rootpassword
  mysql_user:
    file: ../secrets/mysql_user

  wp_admin_password:
    file: ../secrets/wp_admin_password
  wp_user_password:
    file: ../secrets/wp_user_password
  